import sys
'''
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//
// 			     //////////////////////////////////////////////////////////
//  			     //							     //
// 			     //   	        webMANTIS v1.0		     //
//			     //	     (optical photons transport visualization)       //
//			     //							     //
//			     //////////////////////////////////////////////////////////
//
// 
//
//
// ****Disclaimer****
//  This software and documentation (the "Software") were developed at the Food and Drug Administration (FDA) by employees of the Federal Government in
//  the course of their official duties. Pursuant to Title 17, Section 105 of the United States Code, this work is not subject to copyright protection
//  and is in the public domain. Permission is hereby granted, free of charge, to any person obtaining a copy of the Software, to deal in the Software
//  without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, or sell copies of the
//  Software or derivatives, and to permit persons to whom the Software is furnished to do so. FDA assumes no responsibility whatsoever for use by other
//  parties of the Software, its source code, documentation or compiled executables, and makes no guarantees, expressed or implied, about its quality,
//  reliability, or any other characteristic. Further, use of this code in no way implies endorsement by the FDA or confers any advantage in regulatory
//  decisions. Although this software can be redistributed and/or modified freely, we ask that any derivative works bear some notice that they are
//  derived from it, and any modified versions bear some notice that they have been modified. 
//
//
//
//	Filename:	pyPrepareJSONdata.py
//	Updated: 	2/27/2014
//	Author:		Han Dong (US Food and Drug Administration / University of Maryland Baltimore County
//	Email:		han6@umbc.edu
//	Comments:	Reads in visualization data generated by visualMANTIS and converts it to be JSON format to be parsed by the jQuery code.
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// */
'''
inFile = sys.argv[1]

f = open(inFile, 'r')

num = int(f.readline().strip())
jsonData = ''

for i in range(num):
	dataSets = f.readline().strip().split(' ')
	x = dataSets[0]
	y = dataSets[1]
	z = dataSets[2]
	Xc = dataSets[3]
	Yc = dataSets[4]
	terminate = dataSets[5]
	jsonData += '{\"id\":\"'+str(i)+'\",\"x\":\"'+x+'\",\"y\":\"'+y+'\",\"z\":\"'+z+'\",\"Xc\":\"'+Xc+'\",\"Yc\":\"'+Yc+'\",\"terminate\":\"'+terminate+'\"},'
	
print '['+jsonData[:len(jsonData)-1]+']'	

f.close()
